#!/bin/bash
set -e

case "$1" in
    configure)
        mysql -u root -e "CREATE DATABASE IF NOT EXISTS DMJ_VAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        mysql -u root -e "CREATE USER IF NOT EXISTS 'vault_admin'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"
        mysql -u root -e "CREATE USER IF NOT EXISTS 'vault_admin'@'127.0.0.1' IDENTIFIED WITH mysql_native_password BY '';"
        mysql -u root -e "GRANT ALL PRIVILEGES ON DMJ_VAULT.* TO 'vault_admin'@'localhost';"
        mysql -u root -e "GRANT ALL PRIVILEGES ON DMJ_VAULT.* TO 'vault_admin'@'127.0.0.1';"
        mysql -u root -e "FLUSH PRIVILEGES;"
        python3 -m dmj_vault.dbserver.setup_schema
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
esac

#DEBHELPER#
