#!/bin/bash
set -e

case "$1" in
    remove)
        rm -f /etc/nginx/sites-enabled/dmj-vault-apps-api
        if systemctl is-active --quiet nginx; then
            nginx -t && systemctl reload nginx
        fi
        ;;
esac

#DEBHELPER#
