#!/usr/bin/python3
import os
import subprocess
import sys

CONFIG_FILE = '/etc/dmj-vault-apps-api/conf'
CONF_D_DIR = '/etc/dmj-vault-apps-api/conf.d'

NGINX_SITE = '/etc/nginx/sites-available/dmj-vault-apps-api'
NGINX_ENABLED = '/etc/nginx/sites-enabled/dmj-vault-apps-api'

GUNICORN_KEYS = ('GUNICORN_HOST', 'GUNICORN_PORT', 'GUNICORN_WORKERS')
NGINX_KEYS = ('NGINX_HOST', 'NGINX_PORT')


def read_config():
    config = {}

    def parse_file(path):
        with open(path) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                if '=' in line:
                    key, _, value = line.partition('=')
                    config[key.strip()] = value.strip()

    if os.path.isfile(CONFIG_FILE):
        parse_file(CONFIG_FILE)

    if os.path.isdir(CONF_D_DIR):
        for fname in sorted(os.listdir(CONF_D_DIR)):
            if fname.endswith('.conf'):
                parse_file(os.path.join(CONF_D_DIR, fname))

    missing = [k for k in GUNICORN_KEYS + NGINX_KEYS if not config.get(k)]
    if missing:
        sys.exit("%s not set in %s -- run the dmj-vault-apps-api role"
                 % (', '.join(missing), CONFIG_FILE))

    return config


def update_nginx_main():
    config = read_config()
    nginx_host = config['NGINX_HOST']
    nginx_port = config['NGINX_PORT']
    gunicorn_host = config['GUNICORN_HOST']
    gunicorn_port = config['GUNICORN_PORT']

    nginx_config = (
        f"# Auto-generated by dmj-vault-apps-api-nginx-update. Do not edit directly.\n"
        f"# To change nginx settings, edit {CONFIG_FILE} and re-run dmj-vault-apps-api-nginx-update.\n"
        f"\n"
        f"server {{\n"
        f"    listen {nginx_host}:{nginx_port};\n"
        f"    location / {{\n"
        f"        proxy_pass http://{gunicorn_host}:{gunicorn_port};\n"
        f"        proxy_set_header X-Real-IP $remote_addr;\n"
        f"        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"
        f"    }}\n"
        f"}}\n"
    )

    with open(NGINX_SITE, 'w') as f:
        f.write(nginx_config)

    if not os.path.islink(NGINX_ENABLED):
        os.symlink(NGINX_SITE, NGINX_ENABLED)

    subprocess.run(['nginx', '-t'], check=True)
    subprocess.run(['systemctl', 'restart', 'nginx'], check=True)


def main():
    missing = [k for k in GUNICORN_KEYS if not os.environ.get(k)]
    if missing:
        sys.exit("%s not set -- run the dmj-vault-apps-api role"
                 % ', '.join(missing))

    os.execv('/usr/bin/gunicorn', [
        'gunicorn',
        'dmj_vault.apps.api.wsgi:app',
        '--worker-class', 'uvicorn.workers.UvicornWorker',
        '--bind', f"{os.environ['GUNICORN_HOST']}:{os.environ['GUNICORN_PORT']}",
        '--workers', os.environ['GUNICORN_WORKERS'],
    ])
